version: '3'
services:

    php:
      build: .
      ports:
        - 80:80
        - 443:443
      volumes:
        - .:/var/www/html
      depends_on: 
        - db  

    db:
      build:  ./data
      tty: true
      restart: always
      volumes:
          - ./data/mysql:/var/lib/mysql
      environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=phprs    